# This is a basic workflow to help you get started with Actions

name: advanced workflow
env:
  WORKFLOW_VAR: "This variable is declared at the workflow level"

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  firstjob:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: firstjob script
        run: echo Hello, world! This is the first job
      - name: Print to Log
        id: print-to-log
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: ${{ github.actor }}
      - name: time
        run: |
          echo "The time of the greeting was at ${{ steps.print-to-log.outputs.time }}"
        
  secondjob:
    runs-on: ubuntu-latest
    needs: firstjob
    env:
      JOB_VAR: "This is a job variable"
    steps:
      # Runs a set of commands using the runners shell
      - name: secondjob script
        shell: bash
        run: |
          echo this is the second job
          echo and this is a multiline script
      - name: environment variable
        env:
          STEP_VAR: "This variable is declared at the step level"
        run: |
          echo $WORKFLOW_VAR
          echo $JOB_VAR
          echo $STEP_VAR
          echo "This is the $SUPER_SECRET"
          echo $GITHUB_ACTOR
          echo $GITHUB_JOB
          echo $GITHUB_REF
          
